### ISSUE TITLE
Custom test seams to colide with dbt-utils when parameter are different

### ISSUE THREAD

**Issue by fuchsst** [dbt-labs/dbt#3983]
### Describe the bug
After the upgrade from dbt 0.19.2 to 0.20.2 (same problem with 0.21.0-rc2) a custom test with the following interface 
`{% test test_mutually_exclusive_ranges(model, lower_bound_column, upper_bound_column, partition_by, gaps='allowed', load_sequence_column=none, where=none, enabled=true) %}`
before
`{% macro test_mutually_exclusive_ranges(model, lower_bound_column, upper_bound_column, partition_by, gaps='allowed', load_sequence_column=none, where=none, enabled=true) %}`
throws the following error when running `dbt compile` (the same macro worked with dbt 0.19.2):
```
Running with dbt=0.20.2
Encountered an error:
Compilation Error in test mutually_exclusive_ranges_s_attribute_attribute_reference_not_allowed__load_seq__load_ts__l_attribute_attribute_reference_id__coalesce_unload_ts_current_timestamp_ (models/dwh_core_ad_content_yellow/s_attribute_attribute_reference.yml)
  macro 'dbt_macro__test_mutually_exclusive_ranges' takes no keyword argument 'load_sequence_column'
  
  > in macro test_mutually_exclusive_ranges (macros/schema_tests/mutually_exclusive_ranges.sql)
  > called by test mutually_exclusive_ranges_s_attribute_attribute_reference_not_allowed__load_seq__load_ts__l_attribute_attribute_reference_id__coalesce_unload_ts_current_timestamp_ (models/dwh_core_ad_content_yellow/s_attribute_attribute_reference.yml)
```

dbt utils is also installed (maybe it dispatches the wrong one?)
the test is defined as
```
models:
  - name: s_attribute_attribute_reference
    columns:
      ...
    tests:
      - mutually_exclusive_ranges:
          lower_bound_column: load_ts
          upper_bound_column: coalesce(unload_ts, current_timestamp())
          load_sequence_column: load_seq
          partition_by: [l_attribute_attribute_reference_id]
          gaps: not_allowed
          tags: [ monthly ]
```

### Expected behavior
Only required step to upgrade dbt is 
run `pip install dbt==0.21.0-rc2`
bump version in `packages.yml`
run `dbt deps`
change the test jinja from using `test` instead of `macro`
run `dbt compile` (<- this fails with the above error)

### Screenshots and log output
see bug description

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0-rc2
   latest version: 0.20.2

Your version of dbt is ahead of the latest release!

Plugins:
  - redshift: 0.21.0rc2
  - snowflake: 0.21.0rc2
  - postgres: 0.21.0rc2
  - bigquery: 0.21.0rc2
```

**The operating system you're using:**
Ubuntu 21.04 64-bit

**The output of `python --version`:**
Python 3.8.6

### Additional context
Problem both present in dbt 0.20.2 and 0.21.0-rc2

dbt-utils is also installed
`packages.yml`
```
packages:
  - package: dbt-labs/dbt_utils
    version: ["0.7.3"]
```

**Comment by jtcohen6** [comment]
Hey @fuchsst, as part of the switch in v0.20 from generic tests being defined as macros prefixed with `test_` to being `test` blocks, it is no longer necessary to include the `test_` prefix.

Try removing the `test_` prefix from your custom test. I did that, and everything ran for me just fine.
```sql
{% test mutually_exclusive_ranges(
    model,
    lower_bound_column,
    upper_bound_column,
    partition_by,
    gaps='allowed',
    load_sequence_column=none
) %}
   ...
{% endtest %}
```
(By the way, I think you shouldn't need to explicitly define `where` or `enabled` as explicit arguments either, now that both are fully supported as test configs!)
