### ISSUE TITLE
compile_sql in rpc with bad jinja crashes dbt

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt#3890]
### Describe the bug
Attempting to compile a model with the code `{{ log(none['foo']) }}` results in a crash:

```
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
obj = _ForkingPickler.dumps(obj)
File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 462, in __reduce__
raise_compiler_error(f'{self.name} is undefined', node=node)
File "/usr/local/lib/python3.8/dist-packages/dbt/exceptions.py", line 444, in raise_compiler_error
raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in rpc request (from remote system)
foo is undefined

```

### Steps To Reproduce

1. In dbt Cloud set the version of the Development environment to v0.21.0b2
2. Save a single model file with this code: `{{ log(none['foo']) }}`
3. Select the model and click Compile
4. Compile spins infinitely

### Expected behavior
Error message, but no crash.

**The output of `dbt --version`:**
```
0.21.0b2
```

**Comment by barberscott** [comment]
Agree similar and possibly a regression in b2 since you attempted to address this bit of code in #3687 where you killed the recursion error...but now looks like a crash in another place...

**Comment by jtcohen6** [comment]
Thanks for the report @barberscott. Agree that this _feels like_ two steps forward, one step back from #3464. Thanks to the fix in #3687, saving a model with `{{ log(none['foo']) }}` will no longer cause an immediate `500 Internal Server Error`, but if the same content is passed to `compile_sql`, the task will have `state: running` forever (ultimately stopped only by `RPC timeout error`). For what it's worth, I checked with dbt v0.20.2 (which does not include the fix from #3687), and passing this content to `compile_sql` caused the same infinite loop and timeout error—I didn't notice that in https://github.com/dbt-labs/dbt/issues/3464#issuecomment-863523091 because I was distracted by the more glaring 500 error—so this doesn't represent a net-new regression.

It does feel like there's some similarity with #3808, in that dbt clearly encounters an error (here `CompilationException`, there `MacroReturn `) and logs the python traceback, yet the RPC server doesn't surface the error or interrupt its running task. One difference that feels important: dbt tripped the error in #3808 during project parsing. In this case, I can parse the project, even compile the model (CLI `dbt compile` / RPC `compile` method), without seeing any `foo is undefined` errors. It's _only_ when I pass the content to the `compile_sql` method that it trips the undefined error.

If I pass the same content to the `run_sql` method, it trips the same error, but then manages to bounce back—sending the compiled SQL to the database, and returning the result. Weird! You can try this yourself by putting `{{ log(none['foo']) }} select 1 as id` in (e.g.) the dbt Cloud IDE. Pressing "Preview Data" will successfully return `1`, whereas pressing `Compile SQL` will crash the server.

In any case, `run_sql` still does trip the same exception. Here are its logs:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/Users/jerco/dev/product/dbt/core/dbt/clients/jinja.py", line 462, in __reduce__
    raise_compiler_error(f'{self.name} is undefined', node=node)
  File "/Users/jerco/dev/product/dbt/core/dbt/exceptions.py", line 444, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in rpc my_first_query (from remote system)
  foo is undefined
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'Undefined' object
```

So, this is some educated guesswork:
- The compiler error comes from `__reduce__`, a magic method of dbt's custom `Undefined` class, subclassed from `jinja2.Undefined`, and instantiated by `create_undefined`
- The `create_undefined` method is called by `get_environment` when `capture_macros` is turned on
- I know that the RPC SQL commands (`compile_sql`, `run_sql`) do [some kinda funky things](https://github.com/dbt-labs/dbt/blob/6563d09ba7da855c2ed05498d7909bb793f9c4a1/core/dbt/task/rpc/sql_commands.py#L100-L135) to support defining/overriding manifest objects (macros + refs) inline
- Is it possible that, while standing up a Jinja environment for their woozy macro/ref capture logic, the RPC SQL commands are running into a compilation error that other parts of dbt don't see, or (more likely) for which they have other/better handling? I haven't yet managed to pull any compelling circumstantial evidence (i.e. when I add log messages before + after [`_get_exec_node`](https://github.com/dbt-labs/dbt/blob/6563d09ba7da855c2ed05498d7909bb793f9c4a1/core/dbt/task/rpc/sql_commands.py#L161) is called, I see both messages before the exception is logged).
