### ISSUE TITLE
cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module

### ISSUE THREAD

**Issue by leogodin217** [dbt-labs/dbt#3772]
### Describe the bug
Running DBT test with DBT 0.20.1 on MacOS 11.5.2 connecting to Snowflake gives this error:

Encountered an error:
Runtime Error
  cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (/Users/myusername/projects/python_envs/datalab_env/lib/python3.9/site-packages/snowflake/connector/ocsp_asn1crypto.py)

This used to work on an earlier version of DBT 0.19.[something] I tried installing earlier versions but many of them could not be resolved by PIP. 

### Steps To Reproduce
1) Create Python virtualenv: python3 -m venv dbt_env
2) Install DBT: pip install dbt (Currently installs 0.20.1)
3) Create a model 
4) Add tests to schema.yml
5) Run dbt test

Earlier versions of DBT used to work fine. 
### Expected behavior
It should run the tests

### Screenshots and log output

Running with dbt=0.20.1
Found 1 model, 2 tests, 0 snapshots, 0 analyses, 151 macros, 0 operations, 0 seed files, 3 sources, 0 exposures

Encountered an error:
Runtime Error
  cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (/Users/leogodin/projects/python_envs/datalab_env/lib/python3.9/site-packages/snowflake/connector/ocsp_asn1crypto.py)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ *] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.1
   latest version: 0.20.1

Up to date!

Plugins:
  - bigquery: 0.20.1
  - snowflake: 0.20.1
  - redshift: 0.20.1
  - postgres: 0.20.1
```

**The operating system you're using:**
MacOS 11.5.2

**The output of `python --version`:**
Python 3.9.2

### Additional context
After looking on Slack, I found that setting threads to 1 in profiles.yml allows tests to run. Maybe snowflake-connector-python is not threadsafe on Mac?

**Comment by jtcohen6** [comment]
@leogodin217 This is a weird one. From the error you've included, I'd guess that the offending code in `snowflake-connector-python` is in the [`__init__` method of `SnowflakeOCSPAsn1Crypto`](https://github.com/snowflakedb/snowflake-connector-python/blob/9d7559bdab6ea972d69788d9197ae88dadb1f068/src/snowflake/connector/ocsp_asn1crypto.py#L84-L86), which is then called by [`snowflake.connector.tool.dump_certs.main()`](https://github.com/snowflakedb/snowflake-connector-python/blob/9d7559bdab6ea972d69788d9197ae88dadb1f068/src/snowflake/connector/tool/dump_certs.py#L47). I can't tell where or why that tool called, or how it would intersect with multi-threaded execution.

To give us a better shot at debugging this, could I ask you to include the full debug-level logs, either from `logs/dbt.log` or by running `dbt --debug test`? I'm hopeful that it will include a python stacktrace with more details about the specific methods that are calling these methods and tripping this error.

To be clear, I haven't been able to reproduce this behavior locally, using dbt v0.20.2-rc2 (built from `0.20.latest` branch) with `snowflake-connector-python==2.4.6`.

**Comment by leogodin217** [comment]
@jtcohen6 Sorry I missed this. I'll get the log today

**Comment by leogodin217** [comment]
Here's the log. I sanitized it for DB and table names

[dbt_log.log](https://github.com/dbt-labs/dbt/files/7124581/dbt_log.log)

**Comment by jtcohen6** [comment]
@leogodin217 This sure looks like a bug in `snowflake-connector-python`. All dbt-snowflake is doing here is calling `snowflake.connector.connect`:
```
2021-09-07 17:44:58.000276 (MainThread): Traceback (most recent call last):
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 179, in exception_handler
    yield
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 79, in add_query
    cursor = connection.handle.cursor()
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/dbt/contracts/connection.py", line 81, in handle
    self._handle.resolve(self)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/dbt/contracts/connection.py", line 107, in resolve
    return self.opener(connection)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 220, in open
    handle = snowflake.connector.connect(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/__init__.py", line 50, in Connect
    return SnowflakeConnection(**kwargs)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 273, in __init__
    self.connect(**kwargs)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 484, in connect
    self.__open_connection()
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 723, in __open_connection
    self._authenticate(auth_instance)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 984, in _authenticate
    self.__authenticate(self.__preprocess_auth_instance(auth_instance))
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 1003, in __authenticate
    auth.authenticate(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/auth.py", line 241, in authenticate
    ret = self._rest._post_request(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/network.py", line 629, in _post_request
    ret = self.fetch(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/network.py", line 719, in fetch
    ret = self._request_exec_wrapper(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/network.py", line 841, in _request_exec_wrapper
    raise e
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/network.py", line 762, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/network.py", line 1049, in _request_exec
    raise err
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/network.py", line 926, in _request_exec
    raw_ret = session.request(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/ssl_wrap_socket.py", line 81, in ssl_wrap_socket_with_ocsp
    from .ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP
ImportError: cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (/Users/user1/projects/python_envs/dl_env/lib/python3.9/site-packages/snowflake/connector/ocsp_asn1crypto.py)
```

You could confirm that for sure by manually hooking into `snowflake.connector.python`, using the same authentication mechanism that you use with dbt. For example, for user/password:
```python
# run this in a python env with snowflake-connector-python installed

import snowflake.connector

account = <your_snowflake_account>
user = <your_user>
database = <your_database>
schema = <your_schema>
warehouse = <your_warehouse>
role = <your_role>
autocommit = True
client_session_keep_alive = False

handle = snowflake.connector.connect(
    account=account,
    user=user,
    password=password,
    database=database,
    schema=creds.schema,
    warehouse=creds.warehouse,
    role=creds.role,
    autocommit=True,
    client_session_keep_alive=False
)

handle.cursor().execute("select 1 as fun")
```

If you're able to reproduce the error using just the Snowflake connector, I think it would make sense to reopen this issue over there: https://github.com/snowflakedb/snowflake-connector-python/issues

**Comment by leogodin217** [comment]
This code runs fine. I assume because it is single-threaded. I can run "dbt run" fine. It's only "dbt test" that fails when I set more than one thread. Can you point me in a direction that would show the difference between how test handles connections and how run handled connections? I looked through the code and they seem the same.

**Comment by leogodin217** [comment]
Good news. This is fixed in 0.20.2. Everything is working fine now

**Comment by jtcohen6** [comment]
@leogodin217 Ah, that's great news! I don't know which change in particular would have fixed this; I wonder if, by upgrading to v0.20.2, you incidentally installed a new patch of `snowflake-connector-python` that included a fix for this (??).

> Can you point me in a direction that would show the difference between how test handles connections and how run handled connections? I looked through the code and they seem the same.

They really are almost entirely the same. The `test` task inherits most of its methods from the `run` task.

I'm going to close this issue, though I'm still not sure of the root cause. We can re-open if someone encounters the same error again.

**Comment by joleyjol** [comment]
Hi folks - 

I am currently running into the same `ImportError: cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/snowflake/connector/ocsp_asn1crypto.py)`

I'm using snowflake-connector-python 2.7.3, and I've tried using dbt 1.0.0 and 1.0.1.

```
[19:35:05.035] [] [          ] [INFO ] - stdout: dbt version: 1.0.0
[19:35:05.036] [] [          ] [INFO ] - stdout: python version: 3.9.2
[19:35:05.036] [] [          ] [INFO ] - stdout: python path: /usr/bin/python3.9
[19:35:05.036] [] [          ] [INFO ] - stdout: os info: Linux-4.14.252-195.483.amzn2.x86_64-x86_64-with-glibc2.31
```

For me it's happening on `dbt run`, but similarly to above, it only happens when threads > 1.  If I set threads: 1 in my profile the project runs fine.

The error isn't happening when I run locally, or even when I run inside a docker container running locally.  It only happens when I run the container inside our VPC with my profile pointing to a privatelink VPC endpoint.

I ran the job in debug mode and there's quite a bit of output.  Below are a couple of sections that seemed relevant - let me know if there is any additional info I can provide.

```
[19:35:23.681] [] [          ] [INFO ] - stdout: 19:35:23.680789 [info ] [MainThread]: Found 891 models, 1466 tests, 0 snapshots, 0 analyses, 450 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
--
[19:35:23.748] [] [          ] [INFO ] - stdout: 19:35:23.747924 [info ] [MainThread]:
[19:35:23.748] [] [          ] [INFO ] - stdout: 19:35:23.748571 [debug] [MainThread]: Acquiring new snowflake connection "master"
[19:35:23.751] [] [          ] [INFO ] - stdout: 19:35:23.750981 [debug] [ThreadPool]: Acquiring new snowflake connection "list_DBT_DB"
[19:35:23.764] [] [          ] [INFO ] - stdout: 19:35:23.759200 [debug] [ThreadPool]: Acquiring new snowflake connection "list_DBT_DB"
[19:35:23.766] [] [          ] [INFO ] - stdout: 19:35:23.764205 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DB"
[19:35:23.767] [] [          ] [INFO ] - stdout: 19:35:23.766676 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DB"
[19:35:23.768] [] [          ] [INFO ] - stdout: 19:35:23.767632 [debug] [ThreadPool]: On list_DBT_DB: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.768] [] [          ] [INFO ] - stdout:
[19:35:23.768] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.768] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.768] [] [          ] [INFO ] - stdout: 19:35:23.767425 [debug] [ThreadPool]: On list_DBT_DB: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.768] [] [          ] [INFO ] - stdout:
[19:35:23.768] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.768] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.769] [] [          ] [INFO ] - stdout: 19:35:23.767172 [debug] [ThreadPool]: Acquiring new snowflake connection "list_DBT_DB"
[19:35:23.771] [] [          ] [INFO ] - stdout: 19:35:23.768001 [debug] [ThreadPool]: Acquiring new snowflake connection "list_DBT_DB"
[19:35:23.774] [] [          ] [INFO ] - stdout: 19:35:23.768249 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.774] [] [          ] [INFO ] - stdout: 19:35:23.769023 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.775] [] [          ] [INFO ] - stdout: 19:35:23.771185 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DB"
[19:35:23.778] [] [          ] [INFO ] - stdout: 19:35:23.773228 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DB"
[19:35:23.779] [] [          ] [INFO ] - stdout: 19:35:23.778080 [debug] [ThreadPool]: On list_DBT_DB: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.779] [] [          ] [INFO ] - stdout:
[19:35:23.779] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.779] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.781] [] [          ] [INFO ] - stdout: 19:35:23.778874 [debug] [ThreadPool]: On list_DBT_DB: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.781] [] [          ] [INFO ] - stdout:
[19:35:23.781] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.781] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.781] [] [          ] [INFO ] - stdout: 19:35:23.780841 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.783] [] [          ] [INFO ] - stdout: 19:35:23.781217 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.826] [] [          ] [INFO ] - stdout: 19:35:23.825617 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.826] [] [          ] [INFO ] - stdout:
[19:35:23.826] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.826] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.826] [] [          ] [INFO ] - stdout: 19:35:23.826486 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.826] [] [          ] [INFO ] - stdout:
[19:35:23.826] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.826] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.827] [] [          ] [INFO ] - stdout: 19:35:23.826701 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[19:35:23.828] [] [          ] [INFO ] - stdout: 19:35:23.827235 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[19:35:23.829] [] [          ] [INFO ] - stdout: 19:35:23.827443 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: /* {     "app": "dbt",     "dbt_version": "1.0.0",     "profile_name": "pc-dbt-snowflake-db",     "target_name": "dev",     "connection_name": "list_DBT_DB" } */
[19:35:23.829] [] [          ] [INFO ] - stdout:
[19:35:23.829] [] [          ] [INFO ] - stdout:     show terse schemas in database DBT_DB
[19:35:23.829] [] [          ] [INFO ] - stdout:     limit 10000
[19:35:23.829] [] [          ] [INFO ] - stdout: 19:35:23.828005 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.835] [] [          ] [INFO ] - stdout: 19:35:23.828701 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.836] [] [          ] [INFO ] - stdout: 19:35:23.829497 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[19:35:23.838] [] [          ] [INFO ] - stdout: 19:35:23.837611 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.881] [] [          ] [INFO ] - stdout: 19:35:23.881103 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[19:35:23.882] [] [          ] [INFO ] - stdout: 19:35:23.881739 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[19:35:23.882] [] [          ] [INFO ] - stdout: 19:35:23.882335 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.885] [] [          ] [INFO ] - stdout: 19:35:23.885527 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[19:35:23.886] [] [          ] [INFO ] - stdout: 19:35:23.886141 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[19:35:23.887] [] [          ] [INFO ] - stdout: 19:35:23.886780 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[19:35:23.889] [] [          ] [INFO ] - stdout: 19:35:23.886971 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:23.890] [] [          ] [INFO ] - stdout: 19:35:23.887526 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[19:35:23.900] [] [          ] [INFO ] - stdout: 19:35:23.899546 [debug] [ThreadPool]: Opening a new connection, currently in state init
[19:35:24.212] [] [          ] [INFO ] - stdout: 19:35:24.212666 [debug] [ThreadPool]: On list_DBT_DB: Close
[19:35:24.223] [] [          ] [INFO ] - stdout: 19:35:24.222855 [debug] [ThreadPool]: On list_DBT_DB: Close
[19:35:24.290] [] [          ] [INFO ] - stdout: 19:35:24.289760 [debug] [ThreadPool]: SQL status: SUCCESS 6 in 0.52 seconds
[19:35:24.292] [] [          ] [INFO ] - stdout: 19:35:24.291897 [debug] [ThreadPool]: On list_DBT_DB: Close
[19:35:24.377] [] [          ] [INFO ] - stdout: 19:35:24.376958 [debug] [MainThread]: Connection 'master' was properly closed.
[19:35:24.377] [] [          ] [INFO ] - stdout: 19:35:24.377286 [debug] [MainThread]: Connection 'list_DBT_DB' was properly closed.
[19:35:24.377] [] [          ] [INFO ] - stdout: 19:35:24.377680 [debug] [MainThread]: Connection 'list_DBT_DB' was properly closed.
[19:35:24.378] [] [          ] [INFO ] - stdout: 19:35:24.377967 [debug] [MainThread]: Connection 'list_DBT_DB' was properly closed.
[19:35:24.378] [] [          ] [INFO ] - stdout: 19:35:24.378201 [debug] [MainThread]: Connection 'list_DBT_DB' was properly closed.
[19:35:24.378] [] [          ] [INFO ] - stdout: 19:35:24.378684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0e9b7c56a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0e9bf2f520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0ea0189880>]}
[19:35:24.380] [] [          ] [INFO ] - stdout: 19:35:24.379932 [debug] [MainThread]: Flushing usage events
[19:35:24.394] [] [          ] [INFO ] - stdout: 19:35:24.394331 [warn ] [MainThread]: Error sending message, disabling tracking
[19:35:24.396] [] [          ] [INFO ] - stdout: 19:35:24.395678 [error] [MainThread]: Encountered an error:
[19:35:24.396] [] [          ] [INFO ] - stdout: cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/snowflake/connector/ocsp_asn1crypto.py)
```

```
[19:35:24.410] [] [          ] [INFO ] - stdout: Traceback (most recent call last):
--
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/main.py", line 127, in main
[19:35:24.410] [] [          ] [INFO ] - stdout:     results, succeeded = handle_and_check(args)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/main.py", line 192, in handle_and_check
[19:35:24.410] [] [          ] [INFO ] - stdout:     task, res = run_from_args(parsed)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/main.py", line 246, in run_from_args
[19:35:24.410] [] [          ] [INFO ] - stdout:     results = task.run()
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/task/runnable.py", line 476, in run
[19:35:24.410] [] [          ] [INFO ] - stdout:     result = self.execute_with_hooks(selected_uids)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/task/runnable.py", line 431, in execute_with_hooks
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.before_run(adapter, selected_uids)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/task/run.py", line 457, in before_run
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.create_schemas(adapter, selected_uids)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/task/runnable.py", line 565, in create_schemas
[19:35:24.410] [] [          ] [INFO ] - stdout:     existing_schemas_lowered.update(ls_future.result())
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
[19:35:24.410] [] [          ] [INFO ] - stdout:     return self.__get_result()
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
[19:35:24.410] [] [          ] [INFO ] - stdout:     raise self._exception
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
[19:35:24.410] [] [          ] [INFO ] - stdout:     result = self.fn(*self.args, **self.kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/utils.py", line 469, in connected
[19:35:24.410] [] [          ] [INFO ] - stdout:     return func(*args, **kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/task/runnable.py", line 542, in list_schemas
[19:35:24.410] [] [          ] [INFO ] - stdout:     for s in adapter.list_schemas(database_quoted)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/adapters/snowflake/impl.py", line 104, in list_schemas
[19:35:24.410] [] [          ] [INFO ] - stdout:     results = self.execute_macro(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/adapters/base/impl.py", line 992, in execute_macro
[19:35:24.410] [] [          ] [INFO ] - stdout:     result = macro_function(**kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.gen.throw(type, value, traceback)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/adapters/snowflake/connections.py", line 228, in exception_handler
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.rollback_if_open()
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/adapters/base/connections.py", line 104, in rollback_if_open
[19:35:24.410] [] [          ] [INFO ] - stdout:     if conn is not None and conn.handle and conn.transaction_open:
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/contracts/connection.py", line 83, in handle
[19:35:24.410] [] [          ] [INFO ] - stdout:     self._handle.resolve(self)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/contracts/connection.py", line 106, in resolve
[19:35:24.410] [] [          ] [INFO ] - stdout:     return self.opener(connection)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/dbt/adapters/snowflake/connections.py", line 246, in open
[19:35:24.410] [] [          ] [INFO ] - stdout:     handle = snowflake.connector.connect(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/__init__.py", line 50, in Connect
[19:35:24.410] [] [          ] [INFO ] - stdout:     return SnowflakeConnection(**kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/connection.py", line 285, in __init__
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.connect(**kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/connection.py", line 496, in connect
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.__open_connection()
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/connection.py", line 735, in __open_connection
[19:35:24.410] [] [          ] [INFO ] - stdout:     self._authenticate(auth_instance)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/connection.py", line 996, in _authenticate
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.__authenticate(self.__preprocess_auth_instance(auth_instance))
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/connection.py", line 1016, in __authenticate
[19:35:24.410] [] [          ] [INFO ] - stdout:     auth.authenticate(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/auth.py", line 257, in authenticate
[19:35:24.410] [] [          ] [INFO ] - stdout:     ret = self._rest._post_request(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/network.py", line 700, in _post_request
[19:35:24.410] [] [          ] [INFO ] - stdout:     ret = self.fetch(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/network.py", line 790, in fetch
[19:35:24.410] [] [          ] [INFO ] - stdout:     ret = self._request_exec_wrapper(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/network.py", line 912, in _request_exec_wrapper
[19:35:24.410] [] [          ] [INFO ] - stdout:     raise e
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/network.py", line 833, in _request_exec_wrapper
[19:35:24.410] [] [          ] [INFO ] - stdout:     return_object = self._request_exec(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/network.py", line 1086, in _request_exec
[19:35:24.410] [] [          ] [INFO ] - stdout:     raise err
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/network.py", line 988, in _request_exec
[19:35:24.410] [] [          ] [INFO ] - stdout:     raw_ret = session.request(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/requests/sessions.py", line 542, in request
[19:35:24.410] [] [          ] [INFO ] - stdout:     resp = self.send(prep, **send_kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/requests/sessions.py", line 655, in send
[19:35:24.410] [] [          ] [INFO ] - stdout:     r = adapter.send(request, **kwargs)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/requests/adapters.py", line 439, in send
[19:35:24.410] [] [          ] [INFO ] - stdout:     resp = conn.urlopen(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 699, in urlopen
[19:35:24.410] [] [          ] [INFO ] - stdout:     httplib_response = self._make_request(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 382, in _make_request
[19:35:24.410] [] [          ] [INFO ] - stdout:     self._validate_conn(conn)
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 1010, in _validate_conn
[19:35:24.410] [] [          ] [INFO ] - stdout:     conn.connect()
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/vendored/urllib3/connection.py", line 411, in connect
[19:35:24.410] [] [          ] [INFO ] - stdout:     self.sock = ssl_wrap_socket(
[19:35:24.410] [] [          ] [INFO ] - stdout:   File "/usr/local/lib/python3.9/dist-packages/snowflake/connector/ssl_wrap_socket.py", line 81, in ssl_wrap_socket_with_ocsp
[19:35:24.410] [] [          ] [INFO ] - stdout:     from .ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP
[19:35:24.410] [] [          ] [INFO ] - stdout: ImportError: cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/snowflake/connector/ocsp_asn1crypto.py)
```
