### ISSUE TITLE
modules.datetime.date regared as str

### ISSUE THREAD

**Issue by 2rara** [dbt-labs/dbt#4036]
### Describe the bug
Hi, after I updated dbt 0.20.0 to 0.21.0, the following code started giving an error.
`(modules.datetime.date.today()-modules.datetime.timedelta(days=modules.datetime.date.today().weekday())).strftime(“%Y-%m-%d”)`
Error:
`‘str object’ has no attribute ‘strftime’`

I think that the part before .strftime should be datetime.date in Python, so I suspect that dbt is misinterpreting the type.

### Steps To Reproduce
Create a dbt macro using the code above, like
` {% set monday = (modules.datetime.date.today()-modules.datetime.timedelta(days=modules.datetime.date.today().weekday())).strftime("%Y-%m-%d") %}`

Run `dbt compile`.

### Expected behavior
No error.

### Screenshots and log output
'str object' has no attribute 'strftime'

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - bigquery: 0.21.0
  - snowflake: 0.21.0
  - redshift: 0.21.0
  - postgres: 0.21.0
  ```

**The operating system you're using:**
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

**The output of `python --version`:**
Python 2.7.16

### Additional context
I didn't get the error when I used dbt 0.20.0.
